from sqlalchemy.orm import Session
from src.domain.entity.pedido.pedido import Pedido
from src.infrastructure.persistencia.pedidoModel import PedidoModel
from typing import Optional, List
from decimal import Decimal

class PedidoRepository:
    def __init__(self, db: Session):
        self.db = db

    def save(self, pedido: Pedido) -> Pedido:
        pedido_model = PedidoModel(
            id=pedido.id,
            cliente_nome=pedido.cliente_nome,
            descricao=pedido.descricao,
            tipo_entrega=pedido.tipo_entrega,
            preco_total=pedido.preco_total,
            data_entrega=pedido.data_entrega,
            user_id=str(pedido.user_id),
            status=pedido.status
        )
        self.db.add(pedido_model)
        self.db.commit()
        self.db.refresh(pedido_model)
        
        # update id if it was autogenerated and not set
        if not pedido.id:
            pedido.id = pedido_model.id
        return pedido

    def find_by_id(self, pedido_id: int) -> Optional[Pedido]:
        model = self.db.query(PedidoModel).filter(PedidoModel.id == pedido_id).first()
        if not model:
            return None
        
        pedido = Pedido()
        pedido.id = model.id
        pedido.cliente_nome = model.cliente_nome
        pedido.descricao = model.descricao
        pedido.tipo_entrega = model.tipo_entrega
        pedido.preco_total = Decimal(str(model.preco_total)) if model.preco_total else None
        pedido.data_entrega = model.data_entrega
        pedido.user_id = model.user_id
        pedido.status = model.status
        return pedido

    def find_all_by_user(self, user_id: str) -> List[Pedido]:
        models = self.db.query(PedidoModel).filter(PedidoModel.user_id == user_id).all()
        pedidos = []
        for model in models:
            pedido = Pedido()
            pedido.id = model.id
            pedido.cliente_nome = model.cliente_nome
            pedido.descricao = model.descricao
            pedido.tipo_entrega = model.tipo_entrega
            pedido.preco_total = Decimal(str(model.preco_total)) if model.preco_total else None
            pedido.data_entrega = model.data_entrega
            pedido.user_id = model.user_id
            pedido.status = model.status
            pedidos.append(pedido)
        return pedidos

    def delete(self, pedido_id: int) -> bool:
        model = self.db.query(PedidoModel).filter(PedidoModel.id == pedido_id).first()
        if model:
            self.db.delete(model)
            self.db.commit()
            return True
        return False
