# pytest.ini
[pytest]
# Define o diretório raiz dos testes
testpaths = src/test

# Padrão de nomes de arquivos de teste
python_files = test_*.py *_test.py

# Padrão de nomes de funções de teste
python_functions = test* testa*

# Adiciona o diretório src ao PYTHONPATH automaticamente
# Isso permite importar "from domain.entity..." sem erro
pythonpath = src