name: Testes Automatizados

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v2

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Passo 3: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest 

      # Passo 4: Executar testes
      - name: Executar testes
        run: |
          export PYTHONPATH=Projeto-Confeitaria-FastAPI---Python
          pytest --cov=src --cov-fail-under=80 --cov-report=html -v
      
      - name: Upload relatório de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-html
          path: htmlcov


